trainer:
  target: trainer.TrainerDifadapter
checkpoint_path: ./checkpoints/2026-02-05-15-16/ckpts
checkpoint_step: 4000

autoencoderwrapper:
  target: ldm.models.autoencoder.VQModelTorchWrapper
  params:
    freeze_base: True
    shared_encoder:
      target: ldm.models.shared_encoder.SharedEncoder
      ckpt_path: ${checkpoint_path}/shared_encoder_${checkpoint_step}.pth
      params:
        in_channels: 3
        context_dim: 768
        base_channels: 64
        num_blocks: 2
        # act: None
    private_encoder: 
      target: ldm.models.private_encoder.PrivateEncoder
      ckpt_path: ${checkpoint_path}/private_encoder_${checkpoint_step}.pth 
      params:
        in_channels: 3
        out_channels: 256
        base_channels: 64
        num_down: 3
        # act: None


    decoder_adapter: null

discriminator_shared:
  target: ldm.models.discriminator.DomainDiscriminatorS
  ckpt_path: ~
  params:
    in_ch: 768
    hidden: 256
    num_classes: 2

discriminator_private:
  target: ldm.models.discriminator.DomainDiscriminatorP
  ckpt_path: ~
  params:
    in_ch: 256
    hidden: 256
    num_classes: 2
    
autoencoder:
  target: ldm.models.autoencoder.VQModelTorch
  ckpt_path: weights/autoencoder_vq_f4.pth
  use_fp16: True
  tune_decoder: False
  params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      padding_mode: zeros
    lora_tune_decoder: False

unet_wrapper:
  target: models.unet_adagn.UNetModelSwinAdagnV2
  params:
    # private_feat_dim: 256
    # shared_feat_dim: 768
    private_proj:
      target: models.unet_adagn.PrivateProjector
      ckpt_path: ${checkpoint_path}/private_proj_${checkpoint_step}.pth
      params:
        in_dim: 256
        time_embed_dim: 640
    shared_proj:
      target: models.unet_adagn.SharedProjector
      ckpt_path: ${checkpoint_path}/shared_proj_${checkpoint_step}.pth
      params:
        in_ch: 768
        out_ch: 320


model:
  target: models.unet_adagn.UNetModelSwin
  ckpt_path: /share/huayunpeng-nfs/image_enhancement/ResShift/weights/resshift_bicsrx4_s4.pth
  params:
    image_size: 64
    in_channels: 3
    model_channels: 160
    out_channels: 3
    attention_resolutions: [64,32,16,8]
    dropout: 0
    channel_mult: [1, 2, 2, 4]
    num_res_blocks: [2, 2, 2, 2]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 32
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 192
    window_size: 8
    mlp_ratio: 4
    cond_lq: True
    lq_size: 64

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    sf: 4
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 4
    min_noise_level: 0.2
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True

data:
  train:
    type: bicubic_ir_vis
    params:
      ir_source_path: /share/huayunpeng-local/M3FD/dataset/train/ir
      vis_source_path: /share/huayunpeng-local/M3FD/dataset/train/vis
      source_txt_path: ~
      degrade_kwargs:
        scale: 0.25
        activate_matlab: False
        resize_back: False
        pch_size: 256
        pass_smallmaxresize: False
        pass_aug: False
        pass_crop: False
        ir_chn: rgb
        vis_chn: rgb
      transform_type: default
      transform_kwargs:
        mean: 0.5
        std: 0.5
      length: ~
      need_path: False
      im_exts: png
      recursive: False
  # val:
  #   type: bicubic
  #   params:
  #     source_path: /mnt/sfs-common/zsyue/projects/ResShift/SR/testingdata/imagenet256/gt
  #     degrade_kwargs:
  #       scale: 0.25
  #       activate_matlab: True
  #       resize_back: False
  #       pch_size: 256
  #       pass_smallmaxresize: True
  #       pass_aug: True
  #       pass_crop: True
  #     transform_type: default
  #     transform_kwargs:
  #       mean: 0.5
  #       std: 0.5
  #     length: 64
  #     need_path: False
  #     im_exts: png
  #     recursive: False

train:
  # learning rate
  lr: 5e-5                      # learning rate 
  lr_min: 2e-5                      # learning rate 
  lr_schedule: cosin
  warmup_iterations: 500
  # dataloader
  batch: [20, 1]                
  microbatch: 20
  num_workers: 4
  prefetch_factor: 2           
  # optimization settings
  weight_decay: 0               
  ema_rate: 0.999
  iterations: 4000            # total iterations
  train_diffusion: false
  # save logging
  save_freq: 500              # save model every xxx iters           
  log_freq: [200, 2000, 1]         # [training loss, training images, val images]
  loss_coef: 
    lambda_diff: 1.0
    lambda_adv: 0.01
    lambda_private: 0.1
  local_logging: True           # manually save images
  tf_logging: False             # tensorboard logging
  # validation settings
  use_ema_val: True            
  val_freq: ${train.save_freq}
  val_y_channel: True
  val_resolution: ${model.params.lq_size}
  val_padding_mode: reflect
  # training setting
  use_amp: True                # amp training
  seed: 123456                 # random seed
  global_seeding: False
  shared_branch: True
  private_branch: True
  # model compile
  compile:
    flag: False
    mode: reduce-overhead      # default, reduce-overhead
